#!/usr/bin/env bash

# load scripting addition for yabai to work correctly
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###############################################################
#                          CONFIG                           #
###############################################################

# set default layout (can be bsp, stack or float)
yabai -m config layout bsp

# set padding to 8px
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# set modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

# setup spaces
YABAI_NUM_SPACES=8
~/.config/yabai/setup-spaces.sh "$YABAI_NUM_SPACES"

###############################################################
#                          SIGNALS                          #
###############################################################

# restart yabai when a display is added or removed so rules kick in
# https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#quickly-restart-the-yabai-launch-agent
yabai -m signal --add \
    event=display_added \
    action="yabai --restart-service"

yabai -m signal --add \
    event=display_removed \
    action="yabai --restart-service"

# control focus after display, space or window changes
# focus windows on space or display, do not allow Microsoft Teams notification and popup steal focus
# https://github.com/koekeishiya/yabai/issues/719#issuecomment-728140216
# https://github.com/koekeishiya/yabai/issues/74#issuecomment-767904356
yabai -m signal --add \
    event=display_changed \
    action='~/.config/yabai/control-focus.sh'

yabai -m signal --add \
    event=space_changed \
    action='~/.config/yabai/control-focus.sh'

yabai -m signal --add \
    event=window_destroyed \
    action='~/.config/yabai/control-focus.sh'

# minimize Microsoft Teams popup
yabai -m signal --add \
    event=window_title_changed \
    app="^Microsoft Teams$" \
    action='~/.config/yabai/minimize-teams-popup.sh'

# make all non-resizable windows float
# https://github.com/koekeishiya/yabai/issues/1317#issuecomment-1253626905
yabai -m signal --add \
    event=window_created \
    action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# turn on window borders only when there are multiple windows on space
# https://github.com/koekeishiya/yabai/issues/767#issuecomment-752793868
# yabai -m signal --add \
#     event=space_changed \
#     action="~/.config/yabai/control-borders.sh"
# 
# yabai -m signal --add \
#     event=window_created \
#     action="~/.config/yabai/control-borders.sh"
# 
# yabai -m signal --add \
#     event=window_destroyed \
#     action="~/.config/yabai/control-borders.sh"

###############################################################
#                           RULES                           #
###############################################################

# turn off yabai for some apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Steam$" manage=off

# move some apps automatically to specific spaces
yabai -m rule --add app="^Safari$" space=^1
yabai -m rule --add app="^Firefox$" space=^1
yabai -m rule --add app="^iTerm2$" space=2
yabai -m rule --add app="^PyCharm$" space=3
yabai -m rule --add app="^Insomnia$" space=4
yabai -m rule --add app="^Obsidian$" space=^4
yabai -m rule --add app="^Slack$" space=5
yabai -m rule --add app="^Spark$" space=^6
yabai -m rule --add app="^Microsoft Outlook$" space=6
yabai -m rule --add app="^Microsoft Teams$" space=7
yabai -m rule --add app="^Telegram$" space=8

