#!/usr/bin/env bash

# shellcheck source=spaces
source "$(dirname "$0")/spaces"

# load scripting addition for yabai to work correctly
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###############################################################
#                          CONFIG                           #
###############################################################

# set default layout (can be bsp, stack or float)
yabai -m config layout stack

# set padding to 8px
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# set modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

###############################################################
#                          SIGNALS                          #
###############################################################

# setup spaces when display is added or removed
yabai -m signal --add \
    event=display_added \
    action="~/.config/yabai/setup-spaces.sh && ~/.config/yabai/apply-app-spaces.sh"

yabai -m signal --add \
    event=display_removed \
    action="~/.config/yabai/setup-spaces.sh && ~/.config/yabai/apply-app-spaces.sh"

# prevent Teams system dialogs from stealing focus
yabai -m rule --add \
    app="^Microsoft Teams$" \
    subrole="AXSystemDialog" \
    manage=off

# prevent Slack system dialogs from stealing focus
yabai -m rule --add \
    app="^Slack$" \
    subrole="AXSystemDialog" \
    manage=off

# make all non-resizable windows float
# https://github.com/koekeishiya/yabai/issues/1317#issuecomment-1253626905
yabai -m signal --add \
    event=window_created \
    action='yabai -m query --windows --window $YABAI_WINDOW_ID | \
        jq -er ".\"can-resize\" or .\"is-floating\"" || \
        yabai -m window $YABAI_WINDOW_ID --toggle float'

# redirect focus away from sticky windows
# sticky windows appear on every space and can steal focus
yabai -m signal --add \
    event=window_focused \
    action='is_sticky=$(yabai -m query --windows --window $YABAI_WINDOW_ID | \
                jq -r ".\"is-sticky\""); \
        [ "$is_sticky" != "true" ] && exit 0; \
        target=$(yabai -m query --windows --space | \
            jq -r "[.[] | select(.\"is-floating\" == false and .\"is-minimized\" == false)][0].id"); \
        [ -n "$target" ] && [ "$target" != "null" ] && \
            yabai -m window --focus "$target"'

###############################################################
#                          SCRIPTS                          #
###############################################################
# must run before rules so that labels are available
~/.config/yabai/setup-spaces.sh

###############################################################
#                     SPACE-SPECIFIC CONFIG                  #
###############################################################

# use bsp layout for spaces where side-by-side tiling makes more sense
yabai -m config --space music layout bsp
yabai -m config --space misc1 layout bsp
yabai -m config --space misc2 layout bsp

###############################################################
#                           RULES                           #
###############################################################

# turn off yabai for some apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Steam$" manage=off

# move some apps automatically to specific spaces using labels
yabai -m rule --add app="^Safari$" space=^web
yabai -m rule --add app="^Firefox$" space=^web
yabai -m rule --add app="^Alacritty$" space=^code
yabai -m rule --add app="^PyCharm$" space=code
yabai -m rule --add app="^GoLand$" space=code
yabai -m rule --add app="^Obsidian$" space=^productivity
yabai -m rule --add app="^Things$" space=^productivity
yabai -m rule --add app="^1Password$" space=^productivity
yabai -m rule --add app="^Slack$" space=messaging
yabai -m rule --add app="^Microsoft Teams$" space=messaging
yabai -m rule --add app="^Telegram$" space=messaging
yabai -m rule --add app="^Spark$" space=^mail
yabai -m rule --add app="^Microsoft Outlook$" space=mail
yabai -m rule --add app="^Spotify$" space=^music

###############################################################
#                          SCRIPTS                          #
###############################################################
# move existing windows to their designated spaces, because rules only apply to new windows
~/.config/yabai/apply-app-spaces.sh

