#!/usr/bin/env bash

# shellcheck source=spaces
source "$(dirname "$0")/spaces"

# load scripting addition for yabai to work correctly
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
# #configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

###############################################################
#                          CONFIG                           #
###############################################################

# set default layout (can be bsp, stack or float)
yabai -m config layout bsp

# set padding to 8px
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# set modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

###############################################################
#                          SIGNALS                          #
###############################################################

# setup spaces when display is added or removed
yabai -m signal --add \
    event=display_added \
    action="~/.config/yabai/setup-spaces.sh && ~/.config/yabai/apply-app-spaces.sh"

yabai -m signal --add \
    event=display_removed \
    action="~/.config/yabai/setup-spaces.sh && ~/.config/yabai/apply-app-spaces.sh"

# control focus after display, space or window changes
# focus windows on space or display, do not allow overlays to steal focus
# https://github.com/koekeishiya/yabai/issues/719#issuecomment-728140216
# https://github.com/koekeishiya/yabai/issues/74#issuecomment-767904356
yabai -m signal --add \
    event=display_changed \
    action='~/.config/yabai/control-focus.sh'

yabai -m signal --add \
    event=space_changed \
    action='~/.config/yabai/control-focus.sh'

yabai -m signal --add \
    event=window_destroyed \
    action='~/.config/yabai/control-focus.sh'

# minimize Microsoft Teams popup
yabai -m signal --add \
    event=window_title_changed \
    app="^Microsoft Teams$" \
    action='~/.config/yabai/minimize-teams-popup.sh'

# make all non-resizable windows float
# https://github.com/koekeishiya/yabai/issues/1317#issuecomment-1253626905
yabai -m signal --add \
    event=window_created \
    action='~/.config/yabai/float-unresizable.sh'

###############################################################
#                          SCRIPTS                          #
###############################################################
# must run before rules so that labels are available
~/.config/yabai/setup-spaces.sh

###############################################################
#                           RULES                           #
###############################################################

# turn off yabai for some apps
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Steam$" manage=off

# move some apps automatically to specific spaces (using labels from spaces)
yabai -m rule --add app="^Safari$" space=^browser
yabai -m rule --add app="^Firefox$" space=^browser
yabai -m rule --add app="^PyCharm$" space=ide
yabai -m rule --add app="^GoLand$" space=ide
yabai -m rule --add app="^Obsidian$" space=^notes
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Spark$" space=^mail
yabai -m rule --add app="^Microsoft Outlook$" space=mail
yabai -m rule --add app="^Microsoft Teams$" space=teams
yabai -m rule --add app="^Telegram$" space=personal
yabai -m rule --add app="^Spotify$" space=^personal

# move existing windows to their designated spaces (rules only apply to new windows)
~/.config/yabai/apply-app-spaces.sh

